mbox_data:
  filename: "/home/ieuan/repos/gpx-track-render-er/data/mbox/PCT GPS Check-ins.mbox"
  from: "noreply@findmespot.com"
  subject: "Check-in/OK message from SPOT Ieuan's GPS"
gpx_data:
  filename: "/home/ieuan/repos/gpx-track-render-er/data/halfmile_pct/CA_Sec_A_tracks.gpx"
  track_name: "CA Sec A"
start:
  time:
    timestamp: "2016-04-17T15:00:00Z"
    accuracy: "PT2H"
  location:
    lat: ~
    lon: ~
finish:
  time:
    timestamp: "2016-04-18T04:29:23Z"
    accuracy: "PT1S"
  location:
    lat: 33.27477
    lon: -116.64574
timezone: "America/Los_Angeles"
max_distance_from_gpx: 1000